// <auto-generated />
using ErpApp.TruckModule.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpApp.TruckModule.Infrastructure.Migrations
{
    [DbContext(typeof(TruckDbContext))]
    partial class TruckDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErpApp.TruckModule.Domain.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("TruckId");

                    b.ToTable("Trucks", "truckModule");
                });

            modelBuilder.Entity("ErpApp.TruckModule.Domain.Truck", b =>
                {
                    b.OwnsOne("ErpApp.TruckModule.Domain.TrackDescriptiveData", "DescriptiveData", b1 =>
                        {
                            b1.Property<int>("TruckId")
                                .HasColumnType("int");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Description")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("TruckId");

                            b1.HasIndex("Code")
                                .IsUnique();

                            b1.ToTable("Trucks", "truckModule");

                            b1.WithOwner()
                                .HasForeignKey("TruckId");
                        });

                    b.Navigation("DescriptiveData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
